Repository jotoh98/treasureHunt, pull requests merged in 2019-12, with the labels that each got.

#69 moved Test to right location
  src/main/java/com/treasure/hunt/strategy/hider/impl/MaxAreaAngularHintStrategy.java
  src/test/java/com/treasure/hunt/strategy/hider/impl/MaxAreaAngularHintStrategyTest.java
Labels: good first issue

#88 fixed various gui bugs
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/view/CanvasController.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/BeatWidgetController.java
  src/main/resources/layout/beatWidget.fxml
  src/test/java/com/treasure/hunt/game/GameEngineTest.java
Labels: enhancement

#91 Fixed game states being displayed correctly in the log label
  src/main/java/com/treasure/hunt/view/MainController.java
Labels: enhancement

#102 Bugfix/#52 javadoc coverage
  src/main/java/com/treasure/hunt/JavaFxApplication.java
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/game/Move.java
  src/main/java/com/treasure/hunt/game/mods/hideandseek/HideAndSeekGameEngine.java
  src/main/java/com/treasure/hunt/game/mods/hideandseek/package-info.java
  src/main/java/com/treasure/hunt/game/mods/package-info.java
  src/main/java/com/treasure/hunt/game/package-info.java
  src/main/java/com/treasure/hunt/geom/Circle.java
  src/main/java/com/treasure/hunt/jts/PointTransformation.java
  src/main/java/com/treasure/hunt/jts/package-info.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryItem.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryType.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/MaxAreaAngularHintStrategy.java
  src/main/java/com/treasure/hunt/strategy/hint/Hint.java
  src/main/java/com/treasure/hunt/strategy/hint/impl/AngleHint.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/main/java/com/treasure/hunt/utils/JsonFileUtils.java
  src/main/java/com/treasure/hunt/utils/ReflectionUtils.java
  src/main/java/com/treasure/hunt/utils/Requires.java
  src/main/java/com/treasure/hunt/view/CanvasController.java
  src/main/java/com/treasure/hunt/view/Controller.java
  src/main/java/com/treasure/hunt/view/FxUtils.java
  src/main/java/com/treasure/hunt/view/ToolbarController.java
  src/main/java/com/treasure/hunt/view/WidgetBarController.java
  src/main/java/com/treasure/hunt/view/widget/BeatWidgetController.java
  src/main/java/com/treasure/hunt/view/widget/PointInspectorController.java
  src/main/java/com/treasure/hunt/view/widget/SaveAndLoadController.java
  src/main/java/com/treasure/hunt/view/widget/Widget.java
Labels: documentation
