Repository jotoh98/treasureHunt, pull requests merged in 2020-01, with the labels that each got.

#111 Feature/#109 scaling navigator
  src/main/java/com/treasure/hunt/geom/Circle.java
  src/main/java/com/treasure/hunt/geom/Grid.java
  src/main/java/com/treasure/hunt/jts/PointTransformation.java
  src/main/java/com/treasure/hunt/view/CanvasController.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/WidgetBarController.java
  src/main/java/com/treasure/hunt/view/widget/ScaleController.java
  src/main/resources/layout/scaling.fxml
Labels: enhancement

#107 bugfix/#103-gameengine-increased
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/geom/Circle.java
  src/main/java/com/treasure/hunt/strategy/hider/Hider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/MaxAreaAngularHintStrategy.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomAngleHintHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/UserControlledAngleHintHider.java
  src/main/java/com/treasure/hunt/strategy/searcher/Searcher.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/BruteForceSearcher.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/NaiveAngleSearcher.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/NaiveCircleSearcher.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/StrategyFromPaper.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/UserControlledHintSearcher.java
  src/test/java/com/treasure/hunt/game/GameEngineTest.java
  src/test/java/com/treasure/hunt/game/GameManagerTest.java
  src/test/java/com/treasure/hunt/strategy/hider/impl/InstantWinHider.java
  src/test/java/com/treasure/hunt/strategy/hider/impl/RevealingHider.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/MoveOverTreasure1Searcher.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/MoveOverTreasure2Searcher.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/StandingSearcher.java
Labels: enhancement

#101 Feature/#54 strategy run analyzer
  src/main/java/com/treasure/hunt/analysis/Statistic.java
  src/main/java/com/treasure/hunt/analysis/StatisticObject.java
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/ToolbarController.java
  src/main/java/com/treasure/hunt/view/WidgetBarController.java
  src/main/java/com/treasure/hunt/view/widget/BeatWidgetController.java
  src/main/java/com/treasure/hunt/view/widget/PointInspectorController.java
  src/main/java/com/treasure/hunt/view/widget/StatisticsWidgetController.java
  src/main/resources/layout/main.fxml
  src/main/resources/layout/pointInspector.fxml
  src/main/resources/layout/statisticsWidget.fxml
  src/main/resources/layout/style.css
  src/main/resources/layout/widgetBar.fxml
  src/test/java/com/treasure/hunt/game/GameEngineTest.java
Labels: enhancement, question

#108 Enhanced Navigation
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/NavigationController.java
  src/main/resources/layout/main.fxml
  src/main/resources/layout/navigator.fxml
Labels: enhancement

#134 Bugfix/#52 javadoc coverage
  src/main/java/com/treasure/hunt/analysis/StatisticObject.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/jts/geom/Circle.java
  src/main/java/com/treasure/hunt/jts/geom/GeometryAngle.java
  src/main/java/com/treasure/hunt/jts/geom/GeometryLine.java
  src/main/java/com/treasure/hunt/jts/geom/GeometryUtility.java
  src/main/java/com/treasure/hunt/jts/geom/Line.java
  src/main/java/com/treasure/hunt/jts/geom/Ray.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryItem.java
  src/main/java/com/treasure/hunt/utils/EventBusUtils.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/main/java/com/treasure/hunt/utils/SwingUtils.java
Labels: documentation
