Repository jotoh98/treasureHunt, pull requests merged in 2020-04, with the labels that each got.

#287 Adjusted hint request statistic
  src/main/java/com/treasure/hunt/analysis/Statistic.java
Labels: ✅ approved

#253 Feature/#143 circle strategies⭕⭕⭕
  .idea/codeStyles/Project.xml
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/mods/hideandseek/HideAndSeekGameEngine.java
  src/main/java/com/treasure/hunt/jts/CanvasBoundary.java
  src/main/java/com/treasure/hunt/jts/geom/Circle.java
  src/main/java/com/treasure/hunt/jts/geom/GeometryLine.java
  src/main/java/com/treasure/hunt/service/preferences/PreferenceService.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryStyle.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryType.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/FixedTreasureHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/GameField.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/HalfPlaneAdapter_FixedTreasure.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/HalfPlaneAdapter_MobileTreasure.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/MaxAreaAngularHintStrategy.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/MobileTreasureHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomCircleHintHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/StatisticalHider.java
  src/main/java/com/treasure/hunt/strategy/hint/impl/CircleHint.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/CircleSearcher.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/NaiveCircleSearcher.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/main/java/com/treasure/hunt/view/Controller.java
  src/main/java/com/treasure/hunt/view/FxUtils.java
  src/main/java/com/treasure/hunt/view/WidgetBarController.java
  src/main/java/com/treasure/hunt/view/utils/TreeConstructor.java
  src/test/java/com/treasure/hunt/game/GameEngineTest.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/MoveOverTreasure1Searcher.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/MoveOverTreasure2Searcher.java
  src/test/java/com/treasure/hunt/utils/JTSUtilsTest.java
Labels: 🚀 enhancement, 🤖 strategy

#304 bugfix/#301-line-rendering
  src/main/java/com/treasure/hunt/jts/awt/AdvancedShapeWriter.java
  src/main/java/com/treasure/hunt/jts/geom/Line.java
  src/main/java/com/treasure/hunt/utils/Renderer.java
Labels: 🚨 critical fix

#319 prevented NullPointerException in TreeConstructor
  src/main/java/com/treasure/hunt/view/utils/TreeConstructor.java
Labels: ✅ approved, 🖥️ frontend

#318 prevented exception when plotting with empty searcher/engine
  src/main/java/com/treasure/hunt/view/StatisticTableController.java
Labels: ✅ approved

#298 Feature/xy searcher
  src/main/java/com/treasure/hunt/strategy/geom/GeometryStyle.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryType.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/XYSearcher.java
Labels: 🤖 strategy

#314 fixed pin point z-index
  src/main/java/com/treasure/hunt/strategy/geom/GeometryStyle.java
Labels: 🔜 approved

#328 Bugfix/#316 cirlce selectable
  src/main/java/com/treasure/hunt/jts/geom/Circle.java
  src/main/java/com/treasure/hunt/service/select/SelectionService.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryStyle.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryType.java
  src/main/java/com/treasure/hunt/strategy/hint/impl/CircleHint.java
  src/main/java/com/treasure/hunt/utils/EventBusUtils.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/ClickInspectorController.java
Labels: 🖥️ frontend

#311 early exit metric
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/service/preferences/PreferenceService.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/PreferencesWidgetController.java
  src/test/java/com/treasure/hunt/game/EarlyExitTest.java
Labels: ❓ question, 🚀 enhancement

#336 initial position point gets added to rendered items now
  src/main/java/com/treasure/hunt/game/GameManager.java
Labels: 🖥️ frontend

#338 dynamic session update on dropdown selection
  src/main/java/com/treasure/hunt/view/MainController.java
Labels: ✅ approved, 🚀 enhancement

#332 cancel settings save closes window, used commit to add javadoc
  src/main/java/com/treasure/hunt/view/settings/SettingsController.java
Labels: ✅ approved

#337 Fixed #183,#339
  src/main/java/com/treasure/hunt/analysis/Statistic.java
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/game/Turn.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/GameField.java
  src/main/java/com/treasure/hunt/strategy/searcher/SearchPath.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/NaiveAngleSearcher.java
  src/test/java/com/treasure/hunt/strategy/searcher/SearchPathTest.java
Labels: 🔜 approved

#346 Fixes #273 strategy from paper + MinimumRectangleStrategy
  src/main/java/com/treasure/hunt/strategy/geom/GeometryStyle.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryType.java
  src/main/java/com/treasure/hunt/strategy/geom/StatusMessageType.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomHalfPlaneHintHider.java
  src/main/java/com/treasure/hunt/strategy/hint/impl/HalfPlaneHint.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/ExcludedAreasUtils.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/MinimumRectangleStrategy.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/RectangleScanEnhanced.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/TransformForAxisParallelism.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/UpdateMinimalPolygon.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/GeometricUtils.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/LastHintBadSubroutine.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/RoutinesFromPaper.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/StatusMessages.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/StrategyFromPaper.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/test/java/com/treasure/hunt/strategy/searcher/SearchPathTest.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/ExcludedAreaUtilsTest.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/RoutinesFromPaperTest.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/StrategyFromPaperTest.java
Labels: ✅ approved

#341 SteadyDirectionSearcher: Cleanup
  src/main/java/com/treasure/hunt/strategy/searcher/impl/SteadyDirectionSearcher.java
Labels: 🔜 approved

#306 made plot setting mutable editable
  src/main/java/com/treasure/hunt/service/preferences/PreferenceService.java
  src/main/java/com/treasure/hunt/view/StatisticTableController.java
  src/main/java/com/treasure/hunt/view/plot/PlotController.java
  src/main/java/com/treasure/hunt/view/plot/PlotSettingsController.java
  src/main/java/com/treasure/hunt/view/widget/PreferencesWidgetController.java
  src/main/resources/layout/plotSettings.fxml
  src/main/resources/layout/style.css
Labels: ✅ approved

#340 GameEngine: Changed coordinates to points
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/game/mods/hideandseek/HideAndSeekGameEngine.java
  src/test/java/com/treasure/hunt/game/GameEngineTest.java
Labels: 🔜 approved

#294 added rounded display of numeric values
  src/main/java/com/treasure/hunt/service/settings/Settings.java
  src/main/java/com/treasure/hunt/view/StatisticTableController.java
  src/main/java/com/treasure/hunt/view/settings/SettingsController.java
  src/main/java/com/treasure/hunt/view/utils/TreeConstructor.java
  src/main/java/com/treasure/hunt/view/widget/PreferencesWidgetController.java
  src/main/java/com/treasure/hunt/view/widget/StatisticsWidgetController.java
  src/main/resources/layout/preferencesWidget.fxml
  src/main/resources/layout/statisticsTable.fxml
  src/main/resources/layout/style.css
Labels: ✅ approved

#360 mini map implementation
  src/main/java/com/treasure/hunt/jts/awt/PointTransformation.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/ScaleController.java
  src/main/resources/layout/scaling.fxml
Labels: ✅ approved, 🖥️ frontend, 🚀 enhancement

#361 Bugfix/#285 poly tight search area bug
  src/main/java/com/treasure/hunt/strategy/searcher/impl/PolygonStrategy.java
Labels: ✅ approved

#359 Bugfix/#356 and #357 bugs in MinimumRectangleStrategy
  src/main/java/com/treasure/hunt/strategy/hint/impl/HalfPlaneHint.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/MinimumRectangleStrategy.java
Labels: ✅ approved

#343 gameengine cleanup + unittests
  README.md
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/mods/hideandseek/HideAndSeekGameEngine.java
  src/main/java/com/treasure/hunt/jts/geom/Circle.java
  src/test/java/com/treasure/hunt/game/EarlyExitTest.java
  src/test/java/com/treasure/hunt/game/GameEngineTest.java
  src/test/java/com/treasure/hunt/jts/geom/CircleTest.java
  src/test/java/com/treasure/hunt/strategy/searcher/impl/StandingSearcher.java
Labels: 🔜 approved

#288 javadoc
  src/main/java/com/treasure/hunt/analysis/Statistic.java
  src/main/java/com/treasure/hunt/analysis/StatisticAggregation.java
  src/main/java/com/treasure/hunt/analysis/package-info.java
  src/main/java/com/treasure/hunt/cli/package-info.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/game/mods/package-info.java
  src/main/java/com/treasure/hunt/game/package-info.java
  src/main/java/com/treasure/hunt/jts/awt/package-info.java
  src/main/java/com/treasure/hunt/jts/geom/package-info.java
  src/main/java/com/treasure/hunt/jts/package-info.java
  src/main/java/com/treasure/hunt/service/io/SeriesService.java
  src/main/java/com/treasure/hunt/service/io/package-info.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryType.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/FixedTreasureHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/GameField.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/ImpossibleTreasureLocationException.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/InvalidHintException.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomAngleHintHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/StatisticalHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/package-info.java
  src/main/java/com/treasure/hunt/strategy/hint/impl/HalfPlaneHint.java
  src/main/java/com/treasure/hunt/strategy/hint/impl/package-info.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/BruteForceSearcher.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/PolygonStrategy.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/MinimumRectangleStrategy.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/RectangleScanEnhanced.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/minimumRectangleStrategy/TransformForAxisParallelism.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/package-info.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/LastHintBadSubroutine.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/RoutinesFromPaper.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/StrategyFromPaper.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/main/java/com/treasure/hunt/utils/ListUtils.java
  src/main/java/com/treasure/hunt/utils/package-info.java
  src/main/java/com/treasure/hunt/view/package-info.java
  src/main/java/com/treasure/hunt/view/utils/TreeConstructor.java
  src/main/java/com/treasure/hunt/view/widget/ScaleController.java
  src/main/java/com/treasure/hunt/view/widget/package-info.java
Labels: 📄 documentation

#363 condensed css
  src/main/java/com/treasure/hunt/Main.java
  src/main/java/com/treasure/hunt/view/WidgetBarController.java
  src/main/resources/layout/main.fxml
  src/main/resources/layout/preferencesWidget.fxml
  src/main/resources/layout/settings/settings.fxml
  src/main/resources/layout/statisticsTable.fxml
  src/main/resources/layout/style.css
  src/main/resources/layout/toolbarHorizontal.fxml
Labels: 🆘 help wanted, 🖥️ frontend

#367 added a setting for small round size
  src/main/java/com/treasure/hunt/service/io/SeriesService.java
  src/main/java/com/treasure/hunt/service/settings/Settings.java
Labels: 🔜 approved

#371 implemented slow approach metric
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/service/preferences/PreferenceService.java
  src/test/java/com/treasure/hunt/game/TreasureApproachTest.java
Labels: 🔜 approved, 🚀 enhancement

#377 fixed scroll jumping
  src/main/java/com/treasure/hunt/jts/awt/PointTransformation.java
Labels: ✅ approved

#385 see branchname
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/test/java/com/treasure/hunt/utils/JTSUtilsCircleLineIntersectionPointsTest.java
Labels: 🔜 approved

#378 added minimap behaviour
  src/main/java/com/treasure/hunt/service/settings/Settings.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/NavigatorController.java
  src/main/java/com/treasure/hunt/view/widget/StepNavigationController.java
  src/main/resources/layout/main.fxml
  src/main/resources/layout/navigator.fxml
  src/main/resources/layout/scaling.fxml
  src/main/resources/layout/stepNavigator.fxml
Labels: 🖥️ frontend, 🚀 enhancement

#389 its icon timeeeeee!
  src/main/java/com/treasure/hunt/game/Turn.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/BeatWidgetController.java
  src/main/resources/images/icon/bolt.png
  src/main/resources/images/icon/gear.png
  src/main/resources/images/icon/pause.png
  src/main/resources/images/icon/pin.png
  src/main/resources/images/icon/play.png
  src/main/resources/images/icon/plus.png
  src/main/resources/images/icon/power.png
  src/main/resources/images/icon/stop.png
  src/main/resources/images/icon/target.png
  src/main/resources/images/icon/trash.png
  src/main/resources/images/pin.png
  src/main/resources/images/target.png
  src/main/resources/layout/beatWidget.fxml
  src/main/resources/layout/main.fxml
  src/main/resources/layout/preferencesWidget.fxml
  src/main/resources/layout/statisticsTable.fxml
  src/main/resources/layout/style.css
Labels: ✅ approved
