Repository jotoh98/treasureHunt, pull requests merged in 2020-03, with the labels that each got.

#194 fixed taskbar icon not showing up
  src/main/java/com/treasure/hunt/JavaFxApplication.java
  src/main/java/com/treasure/hunt/Main.java
  src/main/resources/images/icon.png
Labels: bug

#192 implemented history list view
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/utils/TreeConstructor.java
  src/main/java/com/treasure/hunt/view/widget/HistoryController.java
  src/main/resources/layout/history.fxml
  src/main/resources/layout/style.css
Labels: enhancement

#203 added preference transparency annotations
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomAngleHintHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomHalfPlaneHintHider.java
  src/main/java/com/treasure/hunt/utils/Preference.java
  src/main/java/com/treasure/hunt/utils/Preferences.java
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/widget/PreferencesWidgetController.java
Labels: enhancement

#200 moved widgets to the corners
  src/main/java/com/treasure/hunt/view/MainController.java
  src/main/java/com/treasure/hunt/view/ToolbarController.java
  src/main/java/com/treasure/hunt/view/WidgetBarController.java
  src/main/java/com/treasure/hunt/view/widget/HistoryController.java
  src/main/java/com/treasure/hunt/view/widget/Widget.java
  src/main/resources/layout/history.fxml
  src/main/resources/layout/main.fxml
  src/main/resources/layout/preferencesWidget.fxml
  src/main/resources/layout/statisticsTable.fxml
  src/main/resources/layout/style.css
  src/main/resources/layout/toolbar.fxml
  src/main/resources/layout/toolbarHorizontal.fxml
  src/main/resources/layout/widgetBar.fxml
Labels: enhancement

#212 initial setup is now rendered correctly
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/game/Turn.java
  src/main/java/com/treasure/hunt/view/widget/HistoryController.java
Labels: Approved

#211 Bugfix/#195 nan hint trace length ratio
  src/main/java/com/treasure/hunt/analysis/Statistic.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomAngleHintHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomHalfPlaneHintHider.java
  src/main/java/com/treasure/hunt/utils/Preference.java
  src/main/java/com/treasure/hunt/view/MainController.java
Labels: Approved

#213 initial setup is now rendered correctly
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomAngleHintHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomHalfPlaneHintHider.java
  src/main/java/com/treasure/hunt/utils/Preference.java
  src/main/java/com/treasure/hunt/view/MainController.java
Labels: Approved

#215 Fix render issue of dropdown
  src/main/java/com/treasure/hunt/service/select/SelectionService.java
  src/main/java/com/treasure/hunt/view/SelectClickedPopUp.java
  src/main/resources/layout/style.css
Labels: Approved, bug

#221 fixes #220
  src/main/java/com/treasure/hunt/service/select/SelectionService.java
Labels: Approved

#224 Fixes/Tweaks for history tree view
  src/main/java/com/treasure/hunt/service/settings/Settings.java
  src/main/java/com/treasure/hunt/view/utils/TreeConstructor.java
  src/main/resources/layout/style.css
Labels: Approved

#243 Feature/#136 polyhedron searcher convex
  src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java
  src/main/java/com/treasure/hunt/jts/geom/Polyhedron.java
  src/main/java/com/treasure/hunt/strategy/geom/GeometryType.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/PolyhedronSearcher.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/main/java/com/treasure/hunt/utils/ListUtils.java
  src/main/java/com/treasure/hunt/view/CanvasController.java
Labels: strategy

#249 Feature/#246 game max turn counter
  src/main/java/com/treasure/hunt/analysis/Statistic.java
  src/main/java/com/treasure/hunt/analysis/StatisticObject.java
  src/main/java/com/treasure/hunt/cli/TreasureHuntRunSeriesCommand.java
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/service/io/SeriesService.java
  src/main/java/com/treasure/hunt/view/StatisticTableController.java
  src/main/java/com/treasure/hunt/view/plot/PlotController.java
  src/main/java/com/treasure/hunt/view/plot/PlotSettingsController.java
  src/main/resources/layout/plotSettings.fxml
  src/main/resources/layout/statisticsTable.fxml
  src/main/resources/layout/style.css
  src/test/java/com/treasure/hunt/service/io/SeriesServiceTest.java
Labels: Approved

#271 added fix for hide and seek
  src/main/java/com/treasure/hunt/game/mods/hideandseek/HideAndSeekGameEngine.java
Labels: Approved, Critical fix

#265 Bugfix/#263 text colour
  src/main/resources/layout/style.css
Labels: ✅ approved, 🖥️ frontend

#277 Brunch/#133 update readme🤓🤓🤓
  README.md
Labels: 📄 documentation, 🔜 approved

#255 Feature/#226 polygon strategy
  src/main/java/com/treasure/hunt/jts/geom/GeometryAngle.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/PolygonStrategy.java
Labels: ✅ approved, 🤖 strategy

#276 BadHalfplaneHintHider😈😈😈
  src/main/java/com/treasure/hunt/strategy/hider/impl/BadHalfplaneHintHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/RandomAngleHintHider.java
Labels: 🔜 approved, 🤖 strategy

#281 Added min treasure distance and fixed treasure
  src/main/java/com/treasure/hunt/service/preferences/PreferenceService.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
Labels: 🔜 approved

#254 Corrected intersection methods
  src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java
  src/main/java/com/treasure/hunt/jts/geom/Line.java
  src/main/java/com/treasure/hunt/jts/geom/Ray.java
  src/main/java/com/treasure/hunt/utils/JTSUtils.java
  src/test/java/com/treasure/hunt/jts/geom/HalfPlaneTest.java
  src/test/java/com/treasure/hunt/jts/geom/RayTest.java
Labels: ✅ approved

#259 added local optimum statistic, fixed solution quotient
  src/main/java/com/treasure/hunt/analysis/Statistic.java
  src/main/java/com/treasure/hunt/analysis/StatisticObject.java
Labels: ✅ approved

#274 More Ray tests 💻 💻 💻
  src/test/java/com/treasure/hunt/jts/geom/RayTest.java
Labels: 🔜 approved

#289 deserialization broken
  src/main/java/com/treasure/hunt/game/GameManager.java
  src/main/java/com/treasure/hunt/view/widget/HistoryController.java
Labels: ✅ approved

#292 Remove x dock
  build.gradle
  src/main/java/com/treasure/hunt/Main.java
Labels: ✅ approved

#269 HinterStrategy: JavaDoc, More Preferences
  src/main/java/com/treasure/hunt/game/GameEngine.java
  src/main/java/com/treasure/hunt/game/mods/hideandseek/HideAndSeekGameEngine.java
  src/main/java/com/treasure/hunt/jts/geom/GeometryAngle.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/FixedTreasureHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/GameField.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/HalfPlaneAdapter_FixedTreasure.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/HalfPlaneAdapter_MobileTreasure.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/MobileTreasureHider.java
  src/main/java/com/treasure/hunt/strategy/hider/impl/StatisticalHider.java
  src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/StrategyFromPaper.java
Labels: ✅ approved, 🤖 strategy
